---
- name: Gunicorn | Ensure gevent is installed
  pip: name=gevent virtualenv={{ djangoapp_virtualenv_dir }} state=present

- name: Gunicorn | Ensure Gunicorn is installed
  pip: name=gunicorn virtualenv={{ djangoapp_virtualenv_dir }} state=present

- name: Gunicorn | Ensure sock dir is present
  file: dest={{ gunicorn_sock_dir }} owner={{ djangoapp_user }} group={{ djangoapp_group }} 
        state=directory

- name: Gunicorn | Ensure start file is installed
  template: src=gunicorn_start.j2 dest={{ djangoapp_virtualenv_dir }}/bin/gunicorn_start 
            owner={{ djangoapp_user }} group={{ djangoapp_group }} mode=0755 backup=yes
  notify: restart supervisor programs

- name: Gunicorn | Add Gunicorn to Supervisor
  template: src=supervisor_gunicorn.j2 dest={{ supervisor_programs_dir }}/gunicorn.conf
  notify:
    - reread supervisor
    - update supervisor
